export const WORLD_CONSTANTS = {
  TILE_SIZE: 50,
  MAP_WIDTH: 100,
  MAP_HEIGHT: 100,
  MAX_PLAYERS: 100,
  VIEW_DISTANCE: 10,
  MAP_MIN_SIZE: 50,
  MAP_MAX_SIZE: 200,
  MAP_RESIZE_THRESHOLD_MIN: 0.2,
  MAP_RESIZE_THRESHOLD_MAX: 0.8,
  NIGHT_VISIBILITY_REDUCTION: 0.3,
  PLAYER_HITBOX_RADIUS: 25,
  PLAYER_MOVEMENT_SPEED: 200,
  GRID_CELL_SIZE: 1000,
  GRID_CELL_OVERLAP: 100
};

export const BALANCE_CONSTANTS = {
  BASE_HEALTH: 100,
  BASE_DAMAGE: 10,
  BASE_SPEED: 1.0,
  XP_LEVEL_MULTIPLIER: 1.2,
  ELO_K_FACTOR: 32,
  ELO_DIMINISHING_RETURNS_THRESHOLD: 2000,
  ITEM_DROP_BASE_CHANCE: 0.1,
  ITEM_DROP_ELO_BONUS_FACTOR: 0.0001,
  ITEM_DROP_REPEAT_PENALTY: 0.5
};